### ISSUE TITLE
http 400 error

### ISSUE THREAD

**Issue by daktak** [web-tech-tw/matrix-line-bridge#12]
```
> matrix-line-bridge@1.0.0 start
> node_modules/.bin/ts-node app.ts

Application is live and listening on port 29330
Client started!
/pub/git/matrix-line-bridge/node_modules/@line/bot-sdk/dist/http.js:89
            return new exceptions_1.HTTPError(err.message, err.response.status, err.response.statusText, err);
HTTPError: Request failed with status code 400
    at HTTPClient.wrapError (/pub/git/matrix-line-bridge/node_modules/@line/bot-sdk/dist/http.js:89:20)
    at /pub/git/matrix-line-bridge/node_modules/@line/bot-sdk/dist/http.js:19:88
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HTTPClient.post (/pub/git/matrix-line-bridge/node_modules/@line/bot-sdk/dist/http.js:33:21) {
  statusCode: 400,
  statusMessage: 'Bad Request',
  originalError: Error: Request failed with status code 400
      at createError (/pub/git/matrix-line-bridge/node_modules/@line/bot-sdk/node_modules/axios/lib/core/createError.js:16:15)
      at settle (/pub/git/matrix-line-bridge/node_modules/@line/bot-sdk/node_modules/axios/lib/core/settle.js:17:12)
      at IncomingMessage.handleStreamEnd (/pub/git/matrix-line-bridge/node_modules/@line/bot-sdk/node_modules/axios/lib/adapters/http.js:269:11)
      at IncomingMessage.emit (node:events:539:35)
      at IncomingMessage.emit (node:domain:475:12)
      at endReadableNT (node:internal/streams/readable:1344:12)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    config: {
      url: 'https://api.line.me/v2/bot/message/push',
      method: 'post',
      data: '{"messages":[{"type":"text","sender":{"name":"abc","iconUrl":"https://xxxx/_matrix/media/r0/download/xxxx/XiNmqCTySiPlgPwgoGMneTdL"},"text":"Do da do"}],"to":"C64c1e75b5b1bbf8aa288c75e70106c70","notificationDisabled":false}',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      transitional: [Object]
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /v2/bot/message/push HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'Authorization: Bearer xxxx+xx+YJk8vIK4FPs4x2ySZx2jCjsuYB2ejLypptwYZyEqNg0rXTziq+xx+xx/1O/w1cDnyilFU=\r\n' +
        'User-Agent: @line/bot-sdk/7.5.0\r\n' +
        'Content-Length: 245\r\n' +
        'Host: api.line.me\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/v2/bot/message/push',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.line.me',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    response: {
      status: 400,
      statusText: 'Bad Request',
      headers: [Object],
      config: [Object],
      request: [ClientRequest],
      data: [Object]
    },
    isAxiosError: true,
    toJSON: [Function: toJSON]
  }
}
```

**Comment by supersonictw** [comment]
Try this?
https://www.line-community.me/en/question/5f743ee4851f74ab463fe007/push-api-400-bad-request

**Comment by daktak** [comment]
How do you get the chat room id? I've been turning on chat mode for the bot and going to https://chat.line.biz/userID/chat/Cxxxx and using that Cxxx. Is that correct?

**Comment by supersonictw** [comment]
> How do you get the chat room id? I've been turning on chat mode for the bot and going to https://chat.line.biz/userID/chat/Cxxxx and using that Cxxx. Is that correct?

That's incorrect.

There is a command:
https://github.com/web-tech-tw/matrix-line-bridge/blob/8ed940d2f376c7d1c0c67fbb90e1b2d8cb3e6aef/src/provider/line/listener/message/text.ts#L35
can help you get your chat room ID correctly with the command "#getChatRoomId".

**Comment by daktak** [comment]
So in the line group , with the bot added, type "getChatRoomId" ? I get nothing from the bot, no log , no response

**Comment by daktak** [comment]
I think my webhook is not working. Is there a good way to test? Verify in the line developers console give
"The webhook returned an HTTP status code other than 200.(404 Not Found)"
Yet the endpoint is reachable for me.
from message or verify
```
147.92.150.195 - - [10/Jul/2022:11:52:39 +1000] "POST /line HTTP/1.1" 404 435 "-" "LineBotWebhook/2.0" "-"
```
from browser
```
192.168.1.10 - - [10/Jul/2022:11:52:07 +1000] "GET /line HTTP/1.1" 200 387 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" "-"
```

**Comment by daktak** [comment]
Ok, I had callback as my webhook, but it is now /webhook
